package com.nway.platform.wform.access.handler;

public enum HandlerType {

	FIELD_GROUP_DATA_CREATE, FIELD_GROUP_DATA_LIST, FIELD_GROUP_DATA_MODIFY, FIELD_GROUP_DATA_QUERY, FIELD_GROUP_DATA_REMOVE,

	FORM_PAGE_DATA_CREATE, FORM_PAGE_DATA_LIST, FORM_PAGE_DATA_MODIFY, FORM_PAGE_DATA_QUERY, FORM_PAGE_DATA_REMOVE;
}
