
CREATE TABLE T_FORM_MODULE (
	MODULE_ID VARCHAR(32) PRIMARY KEY,
	MODULE_NAME VARCHAR(100),
	SUMMARY VARCHAR(255),
	LAST_UPDATE_DATE TIMESTAMP(0) NULL DEFAULT NULL,
	CREATE_DATE TIMESTAMP(0) NULL DEFAULT NULL,
	STATUS INT(1)
);

CREATE TABLE T_FORM_FORMPAGE (
	FORM_ID VARCHAR(32) PRIMARY KEY,
	FORM_NAME VARCHAR(100),
	FORM_TITLE VARCHAR(100),
	PAGE_TYPE   INT(1),
	SUMMARY VARCHAR(255),
	MODULE_ID VARCHAR(32),
	LAST_UPDATE_DATE TIMESTAMP(0) NULL DEFAULT NULL,
	CREATE_DATE TIMESTAMP(0) NULL DEFAULT NULL,
	STATUS INT(1)
);

CREATE TABLE T_FORM_FIELD_GROUP (
	GROUP_ID VARCHAR(32) PRIMARY KEY,
	NAME VARCHAR(64),
	FORMPAGE_ID VARCHAR(32),
	IS_MANUAL INT(1),
	TABLE_NAME VARCHAR(30),
	DISPLAYTYPE INT(1),
	EDITABLE INT(1),
	PRIMARY_KEY_NAME VARCHAR(30),
	MAX_COLUMN_NUM INT(2),
	LAST_UPDATE_DATE TIMESTAMP NULL DEFAULT NULL,
	CREATE_DATE TIMESTAMP NULL DEFAULT NULL,
	STATUS INT(1)
);

CREATE TABLE t_r_field_group (
	GROUP_ID VARCHAR(32),
	FIELD_ID VARCHAR(32),
	ROW_NUM INT(2),
	COLUMN_NUM INT(2),
	COLUMN_SPAN INT(2),
	EDITABLE INT(1),
	SIZE INT(2)
);

CREATE TABLE T_FORM_FIELD (
	FIELD_ID VARCHAR(32) PRIMARY KEY,
	NAME VARCHAR(64),
	DISPLAY VARCHAR(64),
	TYPE VARCHAR(63),
	LAST_UPDATE_DATE TIMESTAMP NULL DEFAULT NULL,
	CREATE_DATE TIMESTAMP NULL DEFAULT NULL,
	STATUS INT(1)
);

CREATE TABLE T_FORM_FIELD_ATTRIBUTE(
	FIELD_GROUP_ID VARCHAR(32),
	FIELD_ID VARCHAR(32),
	ATTR_NAME VARCHAR(64),
	ATTR_VALUE VARCHAR(255),
	STATUS INT(1)
);