
CREATE TABLE T_FORM_FORMPAGE (
	FORM_ID VARCHAR(32) PRIMARY KEY,
	FORM_NAME VARCHAR(100),
	FORM_TITLE VARCHAR(100),
	PAGE_TYPE   INT(1),
	SUMMARY VARCHAR(255),
	MODULE_ID VARCHAR(32),
	LAST_UPDATE_DATE TIMESTAMP,
	CREATE_DATE TIMESTAMP,
	STATUS INT(1)
);

CREATE TABLE T_FORM_FIELD_GROUP (
	GROUP_ID VARCHAR(32) PRIMARY KEY,
	NAME VARCHAR(64),
	FORMPAGEID VARCHAR(32),
	IS_MANUAL INT(1),
	TABLE_NAME VARCHAR(30),
	DISPLAYTYPE INT(1),
	EDITABLE INT(1),
	MAXCOLUMNNUM INT(2),
	LAST_UPDATE_DATE TIMESTAMP,
	CREATE_DATE TIMESTAMP,
	STATUS INT(1)
);

CREATE TABLE T_FORM_FIELD (
	FIELD_ID VARCHAR(32) PRIMARY KEY,
	NAME VARCHAR(64),
	DISPLAY VARCHAR(64),
	TYPE VARCHAR(63),
	ROW_NUM INT(2),
	COLUMN_NUM INT(2),
	COLUMN_SPAN INT(2),
	EDITABLE INT(1),
	LAST_UPDATE_DATE TIMESTAMP,
	CREATE_DATE TIMESTAMP,
	STATUS INT(1)
);

CREATE TABLE T_FORM_FIELD_ATTRIBUTE(
	FIELD_ID VARCHAR(32),
	ATTR_NAME VARCHAR(64),
	ATTR_VALUE VARCHAR(255),
	STATUS INT(1)
);