
CREATE TABLE `T_FORM_FIELD`  (
  `FIELD_ID` varchar(32) NOT NULL,
  `MODULE_ID` varchar(32) NULL DEFAULT NULL,
  `NAME` varchar(64) NULL DEFAULT NULL,
  `DISPLAY` varchar(64) NULL DEFAULT NULL,
  `TYPE` varchar(63) NULL DEFAULT NULL,
  `SIZE` int(3) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` timestamp(0) NULL DEFAULT NULL,
  `CREATE_TIME` timestamp(0) NULL DEFAULT NULL,
  `STATUS` int(1) NULL DEFAULT NULL,
  PRIMARY KEY (`FIELD_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `T_FORM_FIELD_ATTRIBUTE`  (
  `PAGE_ID` varchar(32) NULL DEFAULT NULL,
  `FIELD_NAME` varchar(64) NULL DEFAULT NULL,
  `ATTR_NAME` varchar(64) NULL DEFAULT NULL,
  `ATTR_VALUE` varchar(255) NULL DEFAULT NULL,
  `STATUS` int(1) NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `T_FORM_PAGE`  (
  `PAGE_ID` varchar(32) NOT NULL,
  `PAGE_NAME` varchar(100) NULL DEFAULT NULL,
  `PAGE_TITLE` varchar(100) NULL DEFAULT NULL,
  `PAGE_TYPE` int(1) NULL DEFAULT NULL,
  `IS_MANUAL` int(1) NULL DEFAULT NULL,/** 手动控制，只做不自动产生sql的标记，sql读取方式不变 **/
  `TABLE_NAME` varchar(30) NULL DEFAULT NULL,
  `SUMMARY` varchar(255) NULL DEFAULT NULL,
  `MODULE_ID` varchar(32) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` timestamp(0) NULL DEFAULT NULL,
  `CREATE_TIME` timestamp(0) NULL DEFAULT NULL,
  `STATUS` int(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PAGE_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `T_FORM_MODULE`  (
  `MODULE_ID` varchar(32) NOT NULL,
  `MODULE_NAME` varchar(100) NULL DEFAULT NULL,
  `SUMMARY` varchar(255) NULL DEFAULT NULL,
  `LAST_UPDATE_DATE` timestamp(0) NULL DEFAULT NULL,
  `CREATE_TIME` timestamp(0) NULL DEFAULT NULL,
  `STATUS` int(1) NULL DEFAULT NULL,
  PRIMARY KEY (`MODULE_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `T_FORM_PAGE_FIELD`  (
  `PK_ID` VARCHAR(32) NOT NULL,
  `PAGE_ID` varchar(32) NULL DEFAULT NULL,
  `FIELD_ID` varchar(32) NULL DEFAULT NULL,
  `ROW_NUM` int(2) NULL DEFAULT NULL,/** 如果对应的page类型为列表，则此字段无效 **/
  `COLUMN_NUM` int(2) NULL DEFAULT NULL,
  `COLUMN_SPAN` int(2) NULL DEFAULT NULL,/** 如果对应的page类型为列表，则此字段无效 **/
  `EDITABLE` int(1) NULL DEFAULT NULL,
  IS_CONDITION INT(1) NULL DEFAULT NULL,/** 列表页面是否作为查询条件的标记 **/
  SHOW_IN_WORKITEM INT(1),
  PRIMARY KEY (`PK_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE T_FORM_FLOW (
	PK_ID VARCHAR(32) NOT NULL,
	PAGE_ID VARCHAR(32),
	PD_KEY VARCHAR(255),
	PRIMARY KEY (`PK_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE T_WORK_ITEM (
	ITEM_ID VARCHAR(32) NOT NULL,
	TITLE VARCHAR(255),
	FORM_URL VARCHAR(255),
	TASK_ID VARCHAR(32),
	STATUS INT(1),
	PRIMARY KEY (`ITEM_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

INSERT INTO T_FORM_MODULE (MODULE_ID,MODULE_NAME) VALUES ('100101','firstModule');

INSERT INTO T_FORM_FLOW VALUES('1','1001','simpleApprovalProcess');

INSERT INTO T_FORM_PAGE_FIELD VALUES('1','1001','1',1,1,1,1,0,1,1);
INSERT INTO T_FORM_PAGE_FIELD VALUES('2','1001','2',2,1,1,1,0,0,0);
INSERT INTO T_FORM_PAGE_FIELD VALUES('3','1001','3',2,2,1,1,0,0,0);

INSERT INTO `T_FORM_FIELD` VALUES ('1', NULL, 'title', '标题', 'text', 255, '2017-12-16 20:42:50', '2017-12-16 20:42:52', 1);
INSERT INTO `T_FORM_FIELD` VALUES ('2', NULL, 'note', '注释', 'text', 255, '2017-12-16 20:43:44', '2017-12-16 20:43:47', 1);
INSERT INTO `T_FORM_FIELD` VALUES ('3', NULL, 'content', '内容', 'textarea', 255, '2017-12-16 20:43:44', '2017-12-16 20:43:47', 1);

INSERT INTO `T_FORM_PAGE` VALUES ('1001', 'first_page', ' 第一个页面', 1, 0,'t_auto_1001','测试', '100101', '2017-12-16 20:14:52', '2017-12-16 20:14:54', 1);
